#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx husky add .husky/commit-msg "npx --no-install commitlint -e "
# monorepo 需要在根目录安装husky 然后在指定目录执行上面命令，并在脚本里手动进入真正项目目录
cd vite
npx --no-install commitlint -e 
